#ci
name: Issviewer CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        # cache: 'pip'
    - run: pip install ephem
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - run: npm ci
    - run: npm run build --if-present 

    - name: Install redis cli # so we can test the server
      run: sudo apt-get install -y redis-tools

    - name: Verify that redis is up
      run: redis-cli ping

    - run: npm test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      if: success()
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: markmark345/cs360-issviewer-img